name: Cypress Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cypress  # Altere para o seu subdiretório

    steps:
    - uses: actions/checkout@v4

    - name: Verify package.json exists
      run: |
        if [ ! -f "package.json" ]; then
          echo "::error::package.json not found in ${{ github.workspace }}/frontend"
          ls -la ${{ github.workspace }}
          exit 1
        fi

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        working-directory: ./cypress
        start: npm start
        wait-on: 'http://localhost:3000'
        browser: chrome
        headless: true
