name: Cypress Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
        
    - name: Verify package.json exists
      id: check-package
      run: |
        if [ ! -f "package.json" ]; then
          echo "::error::package.json not found in repository root"
          exit 1
        fi
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: |
        echo "Contents of repository root:"
        ls -la
        npm install
        
    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        working-directory: ./  # ou o diretório onde está seu projeto se não for na raiz
        start: npm start
        wait-on: 'http://localhost:3000'
        browser: chrome
        headless: true
